version: "3.8"
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discount:
    container_name: discount
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nowearbackone123
      - POSTGRES_DB=discountdb
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
  basket.api:
    container_name: basket_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - RedisSettings:Host=basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: C:\Users\casus\Desktop\photos
        target: ./app/wwwroot/photos
  discount.api:
    container_name: discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - "ConnectionStrings:DefaultConnection=User ID=postgres; Password=nowearbackone123; Server=discountdb; Port=5432; Database=discountdb; Integrated Security=true; Pooling=true;"
    ports:
      - "5014:80"
    depends_on:
      - discountdb
  fake_payment.api:
    container_name: fake_payment_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
    ports:
      - "5016:80"
  order.api:
    container_name: order_api
    restart: on-failture
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver.api
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User=sa; Password=Password12*"
    ports:
      - "5015:80"
    depends_on:
      - orderdb
  gateway.api:
    container_name: gateway_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerUrl=http://identityserver.api
    ports:
      - "5001:80"