version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discount:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3.11.13-management
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/FreeCourse.Services.Catalog/Dockerfile
  basket.api:
    image: basket_api_image
    build:
      context: .
      dockerfile: Services/Basket/FreeCourse.Services.Basket/Dockerfile
  photostock.api:
    image: photostock_api_image
    build:
      context: .
      dockerfile: Services/Photostock/FreeCourse.Services.Photostock/Dockerfile
  discount.api:
    image: discount_api_image
    build:
      context: .
      dockerfile: Services/Discount/FreeCourse.Services.Discount/Dockerfile
  fake_payment.api:
    image: fake_payment_api_image
    build:
      context: .
      dockerfile: Services/FakePayment/FreeCourse.Services.FakePayment/Dockerfile
  order.api:
    image: order_api_image
    build:
      context: .
      dockerfile: Services/Order/FreeCourse.Services.Order.API/Dockerfile
  gateway.api:
    image: gateway_api_image
    build:
      context: .
      dockerfile: Gateways/FreeCourse.Gateway/Dockerfile
  frontend.web:
    image: frontend_image
    build:
      context: .
      dockerfile: Frontends/FreeCourse.Web/Dockerfile
volumes:
  catalogdb_volume:
  discount_volume:
  orderdb_volume: