version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discount:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3.11.13-management
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/FreeCourse.Services.Catalog/Dockerfile
volumes:
  catalogdb_volume:
  discount_volume:
  orderdb_volume: